---

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true

extends:
  - 'airbnb-base'

parserOptions:
  ecmaVersion: latest

rules:
  linebreak-style: 0
  "indent": ["error", 4]
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
